<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Aip;

class AipSummaryFormSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Aip::truncate();

        Aip::insert([
            // --- PARENT AIPs (Level 0) - IDs 1-5 ---
            [
                'aipRefCode' => 'AIP-P-001',
                'ppaDescription' => 'Coastal Resource Management Program',
                'implementingOfficeDepartmentLocation' => 'Environment Office',
                'startingDate' => '2025-01-01 00:00:00',
                'completionDate' => '2025-12-31 00:00:00',
                'expectedOutputs' => '10 km of coast rehabilitated',
                'fundingSource' => 'GAA',
                'ps' => 100000.0,
                'mooe' => 250000.0,
                'fe' => 50000.0,
                'co' => 100000.0,
                'total' => 500000.0,
                'ccAdaptation' => 'High',
                'ccMitigation' => 'Low',
                'ccTypologyCode' => 'CCT-A1',
                'parentId' => null,
            ],
            [
                'aipRefCode' => 'AIP-P-002',
                'ppaDescription' =>
                    'Disaster Risk Reduction and Management Training',
                'implementingOfficeDepartmentLocation' => 'DRRM Office',
                'startingDate' => '2025-03-01 00:00:00',
                'completionDate' => '2025-11-30 00:00:00',
                'expectedOutputs' => '5 training sessions conducted',
                'fundingSource' => 'Local Fund',
                'ps' => 50000.0,
                'mooe' => 100000.0,
                'fe' => 10000.0,
                'co' => 0.0,
                'total' => 160000.0,
                'ccAdaptation' => 'Medium',
                'ccMitigation' => 'Medium',
                'ccTypologyCode' => 'CCT-M2',
                'parentId' => null,
            ],
            [
                'aipRefCode' => 'AIP-P-003',
                'ppaDescription' => 'Agricultural Productivity Enhancement',
                'implementingOfficeDepartmentLocation' =>
                    'Agriculture Department',
                'startingDate' => '2025-02-15 00:00:00',
                'completionDate' => '2025-12-15 00:00:00',
                'expectedOutputs' => '200 farmers trained on new techniques',
                'fundingSource' => 'GAA',
                'ps' => 120000.0,
                'mooe' => 300000.0,
                'fe' => 20000.0,
                'co' => 80000.0,
                'total' => 520000.0,
                'ccAdaptation' => 'Low',
                'ccMitigation' => 'High',
                'ccTypologyCode' => 'CCT-A2',
                'parentId' => null,
            ],
            [
                'aipRefCode' => 'AIP-P-004',
                'ppaDescription' => 'Health and Wellness Outreach Program',
                'implementingOfficeDepartmentLocation' => 'Health Office',
                'startingDate' => '2025-04-01 00:00:00',
                'completionDate' => '2025-10-31 00:00:00',
                'expectedOutputs' => '10 community health missions',
                'fundingSource' => 'Local Fund',
                'ps' => 40000.0,
                'mooe' => 80000.0,
                'fe' => 5000.0,
                'co' => 0.0,
                'total' => 125000.0,
                'ccAdaptation' => 'Low',
                'ccMitigation' => 'Low',
                'ccTypologyCode' => 'CCT-G1',
                'parentId' => null,
            ],
            [
                'aipRefCode' => 'AIP-P-005',
                'ppaDescription' => 'IT Infrastructure Upgrade',
                'implementingOfficeDepartmentLocation' => 'IT Department',
                'startingDate' => '2025-05-01 00:00:00',
                'completionDate' => '2025-09-30 00:00:00',
                'expectedOutputs' => 'New server installed and operational',
                'fundingSource' => 'GAA',
                'ps' => 30000.0,
                'mooe' => 50000.0,
                'fe' => 0.0,
                'co' => 300000.0,
                'total' => 380000.0,
                'ccAdaptation' => 'N/A',
                'ccMitigation' => 'N/A',
                'ccTypologyCode' => 'CCT-G2',
                'parentId' => null,
            ],

            // --- LEVEL 1 CHILDREN AIPs (Parent ID references 1-5) - IDs 6-15 ---
            [
                'aipRefCode' => 'AIP-C1-001',
                'ppaDescription' => 'Mangrove Planting Project',
                'implementingOfficeDepartmentLocation' => 'Environment Office',
                'startingDate' => '2025-01-15 00:00:00',
                'completionDate' => '2025-06-30 00:00:00',
                'expectedOutputs' => '5000 mangrove seedlings planted',
                'fundingSource' => 'GAA',
                'ps' => 30000.0,
                'mooe' => 80000.0,
                'fe' => 10000.0,
                'co' => 0.0,
                'total' => 120000.0,
                'ccAdaptation' => 'High',
                'ccMitigation' => 'Medium',
                'ccTypologyCode' => 'CCT-A1',
                'parentId' => 1, // Parent 1
            ],
            [
                'aipRefCode' => 'AIP-C1-002',
                'ppaDescription' => 'Coral Reef Monitoring',
                'implementingOfficeDepartmentLocation' => 'Environment Office',
                'startingDate' => '2025-03-01 00:00:00',
                'completionDate' => '2025-12-01 00:00:00',
                'expectedOutputs' => 'Quarterly monitoring reports',
                'fundingSource' => 'GAA',
                'ps' => 40000.0,
                'mooe' => 60000.0,
                'fe' => 5000.0,
                'co' => 0.0,
                'total' => 105000.0,
                'ccAdaptation' => 'Medium',
                'ccMitigation' => 'Low',
                'ccTypologyCode' => 'CCT-A1',
                'parentId' => 1, // Parent 1
            ],
            [
                'aipRefCode' => 'AIP-C1-003',
                'ppaDescription' => 'Earthquake Preparedness Workshop',
                'implementingOfficeDepartmentLocation' => 'DRRM Office',
                'startingDate' => '2025-04-10 00:00:00',
                'completionDate' => '2025-04-12 00:00:00',
                'expectedOutputs' => '100 attendees trained',
                'fundingSource' => 'Local Fund',
                'ps' => 10000.0,
                'mooe' => 25000.0,
                'fe' => 2000.0,
                'co' => 0.0,
                'total' => 37000.0,
                'ccAdaptation' => 'Medium',
                'ccMitigation' => 'N/A',
                'ccTypologyCode' => 'CCT-M2',
                'parentId' => 2, // Parent 2
            ],
            [
                'aipRefCode' => 'AIP-C1-004',
                'ppaDescription' => 'Flood Evacuation Drill',
                'implementingOfficeDepartmentLocation' => 'DRRM Office',
                'startingDate' => '2025-06-01 00:00:00',
                'completionDate' => '2025-06-05 00:00:00',
                'expectedOutputs' =>
                    'Successful evacuation drill in 2 barangays',
                'fundingSource' => 'Local Fund',
                'ps' => 5000.0,
                'mooe' => 15000.0,
                'fe' => 1000.0,
                'co' => 0.0,
                'total' => 21000.0,
                'ccAdaptation' => 'High',
                'ccMitigation' => 'N/A',
                'ccTypologyCode' => 'CCT-M2',
                'parentId' => 2, // Parent 2
            ],
            [
                'aipRefCode' => 'AIP-C1-005',
                'ppaDescription' => 'Distribution of Certified Seeds',
                'implementingOfficeDepartmentLocation' =>
                    'Agriculture Department',
                'startingDate' => '2025-03-01 00:00:00',
                'completionDate' => '2025-04-30 00:00:00',
                'expectedOutputs' => 'Seeds distributed to 50 farmers',
                'fundingSource' => 'GAA',
                'ps' => 20000.0,
                'mooe' => 50000.0,
                'fe' => 5000.0,
                'co' => 0.0,
                'total' => 75000.0,
                'ccAdaptation' => 'Medium',
                'ccMitigation' => 'High',
                'ccTypologyCode' => 'CCT-A2',
                'parentId' => 3, // Parent 3
            ],
            [
                'aipRefCode' => 'AIP-C1-006',
                'ppaDescription' => 'Irrigation System Repair',
                'implementingOfficeDepartmentLocation' =>
                    'Agriculture Department',
                'startingDate' => '2025-05-01 00:00:00',
                'completionDate' => '2025-08-31 00:00:00',
                'expectedOutputs' => 'Irrigation system repaired in Area A',
                'fundingSource' => 'GAA',
                'ps' => 30000.0,
                'mooe' => 70000.0,
                'fe' => 0.0,
                'co' => 50000.0,
                'total' => 150000.0,
                'ccAdaptation' => 'Medium',
                'ccMitigation' => 'Low',
                'ccTypologyCode' => 'CCT-A2',
                'parentId' => 3, // Parent 3
            ],
            [
                'aipRefCode' => 'AIP-C1-007',
                'ppaDescription' => 'Maternal and Child Health Campaign',
                'implementingOfficeDepartmentLocation' => 'Health Office',
                'startingDate' => '2025-04-15 00:00:00',
                'completionDate' => '2025-05-15 00:00:00',
                'expectedOutputs' => 'Campaign conducted in 3 sitios',
                'fundingSource' => 'Local Fund',
                'ps' => 15000.0,
                'mooe' => 30000.0,
                'fe' => 2000.0,
                'co' => 0.0,
                'total' => 47000.0,
                'ccAdaptation' => 'Low',
                'ccMitigation' => 'N/A',
                'ccTypologyCode' => 'CCT-G1',
                'parentId' => 4, // Parent 4
            ],
            [
                'aipRefCode' => 'AIP-C1-008',
                'ppaDescription' => 'Software Licensing Acquisition',
                'implementingOfficeDepartmentLocation' => 'IT Department',
                'startingDate' => '2025-05-15 00:00:00',
                'completionDate' => '2025-06-15 00:00:00',
                'expectedOutputs' => 'Licenses for 50 workstations procured',
                'fundingSource' => 'GAA',
                'ps' => 5000.0,
                'mooe' => 10000.0,
                'fe' => 0.0,
                'co' => 150000.0,
                'total' => 165000.0,
                'ccAdaptation' => 'N/A',
                'ccMitigation' => 'N/A',
                'ccTypologyCode' => 'CCT-G2',
                'parentId' => 5, // Parent 5
            ],
            [
                'aipRefCode' => 'AIP-C1-009',
                'ppaDescription' => 'Local Network Security Audit',
                'implementingOfficeDepartmentLocation' => 'IT Department',
                'startingDate' => '2025-07-01 00:00:00',
                'completionDate' => '2025-08-31 00:00:00',
                'expectedOutputs' => 'Security audit report completed',
                'fundingSource' => 'GAA',
                'ps' => 10000.0,
                'mooe' => 20000.0,
                'fe' => 0.0,
                'co' => 0.0,
                'total' => 30000.0,
                'ccAdaptation' => 'N/A',
                'ccMitigation' => 'N/A',
                'ccTypologyCode' => 'CCT-G2',
                'parentId' => 5, // Parent 5
            ],
            [
                'aipRefCode' => 'AIP-C1-010',
                'ppaDescription' => 'Coastal Clean-up Drive',
                'implementingOfficeDepartmentLocation' => 'Environment Office',
                'startingDate' => '2025-02-01 00:00:00',
                'completionDate' => '2025-02-02 00:00:00',
                'expectedOutputs' => '50 sacks of trash collected',
                'fundingSource' => 'GAA',
                'ps' => 5000.0,
                'mooe' => 15000.0,
                'fe' => 500.0,
                'co' => 0.0,
                'total' => 20500.0,
                'ccAdaptation' => 'Medium',
                'ccMitigation' => 'Low',
                'ccTypologyCode' => 'CCT-A1',
                'parentId' => 1, // Parent 1
            ],

            // --- LEVEL 2 CHILDREN AIPs (Parent ID references 6-15) - IDs 16-20 ---
            // The IDs for the L1 children are: 6 (C1-001), 7 (C1-002), 8 (C1-003), 11 (C1-006), 13 (C1-008)
            [
                'aipRefCode' => 'AIP-C2-001',
                'ppaDescription' => 'Mangrove Nursery Maintenance',
                'implementingOfficeDepartmentLocation' => 'Environment Office',
                'startingDate' => '2025-01-01 00:00:00',
                'completionDate' => '2025-06-30 00:00:00',
                'expectedOutputs' => 'Nursery sustained for 6 months',
                'fundingSource' => 'GAA',
                'ps' => 5000.0,
                'mooe' => 10000.0,
                'fe' => 0.0,
                'co' => 0.0,
                'total' => 15000.0,
                'ccAdaptation' => 'High',
                'ccMitigation' => 'N/A',
                'ccTypologyCode' => 'CCT-A1',
                'parentId' => 6, // Parent is AIP-C1-001
            ],
            [
                'aipRefCode' => 'AIP-C2-002',
                'ppaDescription' => 'Underwater Camera Procurement',
                'implementingOfficeDepartmentLocation' => 'Environment Office',
                'startingDate' => '2025-03-15 00:00:00',
                'completionDate' => '2025-04-30 00:00:00',
                'expectedOutputs' => '2 underwater cameras procured',
                'fundingSource' => 'GAA',
                'ps' => 0.0,
                'mooe' => 5000.0,
                'fe' => 0.0,
                'co' => 50000.0,
                'total' => 55000.0,
                'ccAdaptation' => 'N/A',
                'ccMitigation' => 'N/A',
                'ccTypologyCode' => 'CCT-A1',
                'parentId' => 7, // Parent is AIP-C1-002
            ],
            [
                'aipRefCode' => 'AIP-C2-003',
                'ppaDescription' => 'Printing of Handouts',
                'implementingOfficeDepartmentLocation' => 'DRRM Office',
                'startingDate' => '2025-04-01 00:00:00',
                'completionDate' => '2025-04-05 00:00:00',
                'expectedOutputs' => '500 copies of training handouts printed',
                'fundingSource' => 'Local Fund',
                'ps' => 0.0,
                'mooe' => 5000.0,
                'fe' => 0.0,
                'co' => 0.0,
                'total' => 5000.0,
                'ccAdaptation' => 'N/A',
                'ccMitigation' => 'N/A',
                'ccTypologyCode' => 'CCT-M2',
                'parentId' => 8, // Parent is AIP-C1-003
            ],
            [
                'aipRefCode' => 'AIP-C2-004',
                'ppaDescription' => 'Purchase of Cement and Pipes',
                'implementingOfficeDepartmentLocation' =>
                    'Agriculture Department',
                'startingDate' => '2025-05-15 00:00:00',
                'completionDate' => '2025-06-15 00:00:00',
                'expectedOutputs' => 'Materials for repair purchased',
                'fundingSource' => 'GAA',
                'ps' => 0.0,
                'mooe' => 10000.0,
                'fe' => 0.0,
                'co' => 30000.0,
                'total' => 40000.0,
                'ccAdaptation' => 'Medium',
                'ccMitigation' => 'N/A',
                'ccTypologyCode' => 'CCT-A2',
                'parentId' => 11, // Parent is AIP-C1-006
            ],
            [
                'aipRefCode' => 'AIP-C2-005',
                'ppaDescription' => 'Installation and Configuration',
                'implementingOfficeDepartmentLocation' => 'IT Department',
                'startingDate' => '2025-06-01 00:00:00',
                'completionDate' => '2025-06-30 00:00:00',
                'expectedOutputs' => 'New software deployed',
                'fundingSource' => 'GAA',
                'ps' => 5000.0,
                'mooe' => 5000.0,
                'fe' => 0.0,
                'co' => 0.0,
                'total' => 10000.0,
                'ccAdaptation' => 'N/A',
                'ccMitigation' => 'N/A',
                'ccTypologyCode' => 'CCT-G2',
                'parentId' => 13, // Parent is AIP-C1-008
            ],
        ]);
    }
}
