<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ChartOfAccount;

class ChartOfAccountSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing records
        ChartOfAccount::query()->delete();

        $expenseAccounts = $this->getExpenseAccounts();

        // Create a mapping of account numbers to IDs for parent relationships
        $idMap = [];

        foreach ($expenseAccounts as $index => $account) {
            // Create the account without parent_id first
            $createdAccount = ChartOfAccount::create([
                'account_number' => $account['account_number'],
                'account_title' => $account['account_title'],
                'account_type' => 'EXPENSE',
                'expense_class' => $account['expense_class'],
                'account_series' => $account['account_series'],
                'parent_id' => null, // Will be set later
                'level' => $account['level'],
                'is_postable' => $account['is_postable'],
                'is_active' => true,
                'normal_balance' => 'DEBIT',
                'description' => $account['account_title'],
            ]);

            // Store the ID mapping
            $idMap[$account['account_number']] = $createdAccount->id;
        }

        // Now update parent relationships using the ID map
        foreach ($expenseAccounts as $account) {
            if (isset($account['parent_number']) && $account['parent_number']) {
                $parentId = $idMap[$account['parent_number']] ?? null;
                if ($parentId) {
                    ChartOfAccount::where(
                        'account_number',
                        $account['account_number'],
                    )->update(['parent_id' => $parentId]);
                }
            }
        }
    }

    private function getExpenseAccounts(): array
    {
        return [
            // Personnal Services 100
            // [
            //     'account_number' => '5-01-00-000',
            //     'account_title' => 'Personnel Services',
            //     'expense_class' => null, // Header account
            //     'account_series' => '5-01',
            //     'level' => 1,
            //     'is_postable' => false,
            // ],
            // [
            //     'account_number' => '5-01-01-000',
            //     'account_title' => 'Salaries and Wages',
            //     'expense_class' => 'PS',
            //     'account_series' => '5-01',
            //     'parent_number' => '5-01-00-000',
            //     'level' => 2,
            //     'is_postable' => false,
            // ],
            [
                'account_number' => '5-01-01-010',
                'account_title' => 'Salaries and Wages - Regular',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-01-020',
                'account_title' => 'Salaries and Wages - Casual/Contractual',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-010',
                'account_title' => 'PERA',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-020',
                'account_title' => 'RA',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-030',
                'account_title' => 'TA',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-040',
                'account_title' => 'Clothing Allowance',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-050',
                'account_title' => 'Subsistence Allowance',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-060',
                'account_title' => 'Laundry Allowance',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-070',
                'account_title' => 'Quarters Allowance',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-080',
                'account_title' => 'Productivity Incentive Allowance (PEI)',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-090',
                'account_title' => 'Overseas Allowance',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-100',
                'account_title' => 'Honoraria',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-110',
                'account_title' => 'Hazard Pay',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-120',
                'account_title' => 'Longevity Pay',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-130',
                'account_title' => 'Overtime and Night Pay',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-140',
                'account_title' => 'Year End Bonus',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-150',
                'account_title' => 'Cash Gift',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-02-990',
                'account_title' => 'Other Bonuses and Allowances',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-03-010',
                'account_title' => 'Retirement & Life Insurance Contributions',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-03-020',
                'account_title' => 'Pag-ibig Contributions',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-03-030',
                'account_title' => 'Philhealth Contributions',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-03-040',
                'account_title' => 'Employees Compensation Insurance Premiums',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-03-050',
                'account_title' => 'Provident/Welfare Fund Contribution',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-04-010',
                'account_title' => 'Pension Benefits',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-04-020',
                'account_title' => 'Retirement Gratuity',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-04-030',
                'account_title' => 'Terminal Leave Benefits',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-01-04-990',
                'account_title' => 'Other Personnel Benefits ',
                'expense_class' => 'PS',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],

            // Maintenance and Other Operating Expenditures 200
            [
                'account_number' => '5-02-01-010',
                'account_title' => 'Traveling Expenses - Local',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-01-020',
                'account_title' => 'Traveling Expenses - Foreign',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-02-010',
                'account_title' => 'Training Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-02-020',
                'account_title' => 'Scholarship Grants/Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-010',
                'account_title' => 'Office Supplies Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-020',
                'account_title' => 'Accountable Forms Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-030',
                'account_title' => 'Non-Accountable Forms Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-040',
                'account_title' => 'Animal/Zoological Supplies Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-050',
                'account_title' => 'Food Supplies Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-060',
                'account_title' => 'Welfare Goods Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-070',
                'account_title' => 'Drugs and Medicines Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-080',
                'account_title' => 'Medical, Dental and Laboratory Supplies Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-090',
                'account_title' => 'Fuel, Oil and Lubricants Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-100',
                'account_title' => 'Agricultural and Marine Supplies Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-110',
                'account_title' => 'Textbooks and Instructional Materials Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-120',
                'account_title' => 'Military, Police and Traffic Supplies Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-130',
                'account_title' => 'Chemical and Filtering Supplies Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-210',
                'account_title' => 'Semi-Expendable Machinery and Equipment Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-220',
                'account_title' => 'Semi-Expendable Furniture, Fixtures and Books Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-03-990',
                'account_title' => 'Other Supplies and Materials Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-04-010',
                'account_title' => 'Water Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-04-020',
                'account_title' => 'Electricity Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-05-010',
                'account_title' => 'Postage and Courier Services',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-05-020',
                'account_title' => 'Telephone Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-05-030',
                'account_title' => 'Internet Subscription Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-05-040',
                'account_title' => 'Cable, Satellite, Telegraph and Radio Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-06-010',
                'account_title' => 'Awards and Rewards Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-06-020',
                'account_title' => 'Prizes',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-07-010',
                'account_title' => 'Survey Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-07-020',
                'account_title' => 'Research, Exploration and Development Expense',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-08-010',
                'account_title' => 'Demolition and Relocation Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-08-020',
                'account_title' => 'Desilting and Dredging Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-09-010',
                'account_title' => 'Generation, Transmission and Distribution Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-10-010',
                'account_title' => 'Confidential Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-10-020',
                'account_title' => 'Intelligence Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-10-030',
                'account_title' => 'Extraordinary and Miscellaneous Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-11-010',
                'account_title' => 'Legal Services',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-11-020',
                'account_title' => 'Auditing Services',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-11-030',
                'account_title' => 'Consultancy Services',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-11-990',
                'account_title' => 'Other Professional Services',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-12-010',
                'account_title' => 'Environmental/Sanitary Services',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-12-020',
                'account_title' => 'Janitorial Services',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-12-030',
                'account_title' => 'Security Services',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-12-990',
                'account_title' => 'Other General Services',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-13-010',
                'account_title' => 'Repair and Maintenance - Investment Property',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-13-020',
                'account_title' => 'Repair and Maintenance - Land Improvements',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-13-030',
                'account_title' => 'Repair and Maintenance - Infrastructure Asset',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-13-040',
                'account_title' => 'Repair and Maintenance - Buildings and Other Structures',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-13-050',
                'account_title' => 'Repair and Maintenance - Machinery and Equipment',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-13-060',
                'account_title' => 'Repair and Maintenance - Transportation Equipment',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-13-070',
                'account_title' => 'Repair and Maintenance - Furniture and Fixtures',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-13-080',
                'account_title' => 'Repair and Maintenance - Leased Assets',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-13-090',
                'account_title' => 'Repair and Maintenance - Leased Assets Improvements',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-13-990',
                'account_title' => 'Repair and Maintenance - Other Property, Plant & Equipment',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-14-020',
                'account_title' => 'Subsidy to National Government Agencies',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-14-030',
                'account_title' => 'Subsidy to Other Local Government Units',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-14-060',
                'account_title' => 'Subsidy to Other Funds',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-14-070',
                'account_title' => 'Subsidy to General Fund Proper/Special accounts',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-14-080',
                'account_title' => 'Subsidy to Local Economic Enterprise / Public Utilities',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-14-990',
                'account_title' => 'Subsidy - Others',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-15-010',
                'account_title' => 'Transfers of Unspent Current Year DRRM funds to Trust Fund',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-15-020',
                'account_title' => 'Transfers for Project Equity Share / LGU Counterpart',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-16-010',
                'account_title' => 'Taxes, Duties and Licenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-16-020',
                'account_title' => 'Fidelity Bond Premiums',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-16-030',
                'account_title' => 'Insurance Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-99-010',
                'account_title' => 'Advertising Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-99-020',
                'account_title' => 'Printing and Publication Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-99-030',
                'account_title' => 'Representation Expenses (ex. meals and snacks)',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-99-040',
                'account_title' => 'Transportation and Delivery Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-99-050',
                'account_title' => 'Rent Expense',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-99-060',
                'account_title' => 'Membership Dues & Cont. To Organization',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-99-070',
                'account_title' => 'Subscription Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-99-080',
                'account_title' => 'Donations',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '5-02-99-990',
                'account_title' => 'Other Maintenance and Operating Expenses',
                'expense_class' => 'MOOE',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],

            // Capital Outlay 300
            [
                'account_number' => '1-07-01-010',
                'account_title' => 'Land',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-02-990',
                'account_title' => 'Other Land Improvements',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-03-010',
                'account_title' => 'Road Networks',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-03-020',
                'account_title' => 'Flood Control System',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-03-030',
                'account_title' => 'Sewer Systems',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-03-040',
                'account_title' => 'Water Supply Systems',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-03-050',
                'account_title' => 'Power Supply Systems',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-03-060',
                'account_title' => 'Communication Networks',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-03-070',
                'account_title' => 'Seaport Systems',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-03-080',
                'account_title' => 'Airport Systems',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-03-090',
                'account_title' => 'Park, Plazas and Monuments',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-03-990',
                'account_title' => 'Other Infrastructure Assets',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-04-010',
                'account_title' => 'Buildings',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-04-020',
                'account_title' => 'School Buildings',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-04-030',
                'account_title' => 'Hospitals and Health Centers',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-04-040',
                'account_title' => 'Markets',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-04-050',
                'account_title' => 'Slaughterhouses',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-04-060',
                'account_title' => 'Hostels and Dormitories',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-04-990',
                'account_title' => 'Other Structures',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-010',
                'account_title' => 'Machinery',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-020',
                'account_title' => 'Office Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-030',
                'account_title' => 'Information and Communication Technology Equip.',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-040',
                'account_title' => 'Agricultural and Forestry Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-050',
                'account_title' => 'Marine and Fishery Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-060',
                'account_title' => 'Airport Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-070',
                'account_title' => 'Communication Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-080',
                'account_title' => 'Construction and Heavy Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-090',
                'account_title' => 'Disaster Response and Rescue Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-100',
                'account_title' => 'Military, Police and Security Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-110',
                'account_title' => 'Medical Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-120',
                'account_title' => 'Printing Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-130',
                'account_title' => 'Sports Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-140',
                'account_title' => 'Technical and Scientific Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-05-990',
                'account_title' => 'Other Machinery and Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-06-010',
                'account_title' => 'Motor Vehicles',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-06-020',
                'account_title' => 'Trains',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-06-030',
                'account_title' => 'Aircraft and Aircrafts Ground Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-06-040',
                'account_title' => 'Watercrafts',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-06-990',
                'account_title' => 'Other Transportation Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-07-010',
                'account_title' => 'Furniture and Fixtures',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-07-020',
                'account_title' => 'Books',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-99-010',
                'account_title' => 'Work/Zoo Animals',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-07-99-990',
                'account_title' => 'Other Property, Plant, and Equipment',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-08-01-010',
                'account_title' => 'Breeding Stocks',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-08-01-020',
                'account_title' => 'Plants and Trees',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-08-01-030',
                'account_title' => 'Aquaculture',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-08-01-990',
                'account_title' => 'Other Bearer Biological Assets',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-09-01-010',
                'account_title' => 'Patents / Copyrights',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-09-01-020',
                'account_title' => 'Computer Software',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
            [
                'account_number' => '1-09-01-990',
                'account_title' => 'Other Intangible Assets',
                'expense_class' => 'CO',
                'account_series' => null,
                'parent_number' => null,
                'level' => 0,
                'is_postable' => true,
            ],
        ];
    }
}
